apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
    spec:
      containers:
      - image: quangtrang1111/udagram-frontend
        name: udagram-frontend
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
