apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: quangtrang1111/reverseproxy
        name: reverseproxy
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
